### ISSUE TITLE
404 error with White Label Domains

### ISSUE THREAD

**Issue by tomarthur** [RadiusNetworks/flybuy-documentation#27]
The links for iOS and Android information are not properly configured on this page.

https://www.radiusnetworks.com/developers/flybuy/#/integrations/white-label-domains

<img width="950" alt="Screen Shot 2020-11-09 at 11 01 19 " src="https://user-images.githubusercontent.com/1641760/98572168-f1062b80-227a-11eb-8613-b61ced4ee982.png">

**Comment by jnebeker** [comment]
While we're fixing this we can link to the page that hosts deep linking info for both platforms: https://www.radiusnetworks.com/developers/flybuy/#/sdk/deep_linking

**Comment by tomarthur** [comment]
Closing due to wrong location to make PR.
